### ISSUE TITLE
Forcing array with null as value results in array with single null value

### ISSUE THREAD

**Issue by karoraita** [CommunityHiQ/Frends.Community.JSON.EnforceJSONTypes#4]
JSON such as this
`{
    "arrays": [
        {
            "array": null
        },
        {
            "array": {
                "prop": null
            }
        }
    ]
}`

end up forced as:
`{
    "arrays": [
        {
            "array": [
                null
            ]
        },
        {
            "array": [
                {
                    "prop": null
                }
            ]
        }
    ]
}`

where array has Count of 1 instead of 0.

Expected result is:
`{
    "arrays": [
        {
            "array": null
        },
        {
            "array": [
                {
                    "prop": null
                }
            ]
        }
    ]
}`

**Comment by Svenskapojkarna** [comment]
This issue has been moved to https://github.com/CommunityHiQ/Frends.Community.JSON/issues/3
